/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.pfr.C.swig;

public class image {
  public static long quantification(int pixelR, int pixelV, int pixelB) {
    return imageJNI.quantification(pixelR, pixelV, pixelB);
  }

  public static int indexationImage(String dossierFichier, String nomFichierAIndexer, String nomFichierStockage) {
    return imageJNI.indexationImage(dossierFichier, nomFichierAIndexer, nomFichierStockage);
  }

  public static int comparaisonImage(String dossierFichier, String nomFichierAComparer, String fichierDescripteur, FICHIER listeFichiers) {
    return imageJNI.comparaisonImage(dossierFichier, nomFichierAComparer, fichierDescripteur, FICHIER.getCPtr(listeFichiers), listeFichiers);
  }

}
